name: Download from OneDrive
on:
  pull_request:
    branches: [dev]
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download from OneDrive
      uses: victordmontero/onedrive-download-action@v1.0.2
      with:
        file: /VerifoneInstaller/VerifoneInstallerFilesSmall.7z
        output: VerifoneInstallerFilesSmall.7z
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: VerifoneInstallerFilesSmall.7z
        path: VerifoneInstallerFilesSmall.7z
        retention-days: 1
